# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.test_pb2 as test__pb2


class mathServicesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.surface = channel.unary_unary(
        '/test.mathServices/surface',
        request_serializer=test__pb2.surfaceRequest.SerializeToString,
        response_deserializer=test__pb2.surfaceReply.FromString,
        )
    self.volume = channel.unary_unary(
        '/test.mathServices/volume',
        request_serializer=test__pb2.volumeRequest.SerializeToString,
        response_deserializer=test__pb2.volumeReply.FromString,
        )


class mathServicesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def surface(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def volume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_mathServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'surface': grpc.unary_unary_rpc_method_handler(
          servicer.surface,
          request_deserializer=test__pb2.surfaceRequest.FromString,
          response_serializer=test__pb2.surfaceReply.SerializeToString,
      ),
      'volume': grpc.unary_unary_rpc_method_handler(
          servicer.volume,
          request_deserializer=test__pb2.volumeRequest.FromString,
          response_serializer=test__pb2.volumeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'test.mathServices', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
